### ISSUE TITLE
favicon, imagen y descripción 

### ISSUE THREAD

**Issue by pdaire** [ciudadanointeligente/municipales-2012#2]
no están definidos los meta para redes sociales y el favicon está en el home y es el de candideit.org

**Comment by pdaire** [comment]
@kathemalis esto es lo que hay que poner en alguna parte de las páginas
ejemplo deldichoalhecho:

```
<meta property="og:image" content="http://deldichoalhecho.cl/wp-content/themes/musicpro/images/default_avatar.jpg"/>
    <meta property="og:description" content="¿Se cumplen las promesas del programa de gobierno?"/>
```

**Comment by pdaire** [comment]
@kathemalis puedes fijarte en candideit.org cómo poner el favicon

**Comment by kathemalis** [comment]
Favicon OK ahora solo falta la imegen de Meta Redes sociales, que aun no se qué mostrar-
